quorabase/urls.py
from django.urls import path
from . import views
from .views import (
    QuestionListView,
    QuestionDetailView,
    AskQuestionView,
    QuestionUpdateView,
    QuestionDeleteView,
    AnswerView,
    AnswerUpdateView,
    AnswerDeleteView,
    upvote_answer,
    upvote_question,
    AboutUser,
    UserPostQuestions,
    UserPostAnswers,
)

urlpatterns = [
    path("", QuestionListView.as_view(), name="quora-home"),
    path("question/<int:pk>/", QuestionDetailView.as_view(), name="question-detail"),
    path("question/new/", AskQuestionView.as_view(), name="ask-question"),
    path(
        "question/<int:pk>/update/",
        QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "question/<int:pk>/delete/",
        QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path("question/<int:pk>/answer/", AnswerView.as_view(), name="question-answer"),
    path(
        "question/<int:question_pk>/answer/<int:answer_pk>/<str:username>/update/",
        AnswerUpdateView.as_view(template_name="quorabase/answer_form.html"),
        name="answer-update",
    ),
    path(
        "question/<int:question_pk>/answer/<int:answer_pk>/delete/",
        AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path("question/upvote/<int:question_id>", upvote_question, name="upvote-question"),
    path(
        "answer/upvote/<int:answer_id>/",
        upvote_answer,
        name="upvote-answer",
    ),
    path("user/<str:username>/", AboutUser.as_view(), name="about-user"),
    path(
        "user/<str:username>/questions/",
        UserPostQuestions.as_view(),
        name="user-questions",
    ),
    path(
        "user/<str:username>/answers/", UserPostAnswers.as_view(), name="user-answers"
    ),
]

quorabase/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Question(models.Model):  # Table name quorabase_question

    title = models.CharField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    vote = models.ManyToManyField(User, related_name="question_vote", blank=True)

    def __str__(self) -> str:
        return f"{self.title}"

    def get_absolute_url(
        self,
    ):  # Setting the instance of a specific question to the question detail url.
        return reverse("question-detail", kwargs={"pk": self.pk})


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    vote = models.ManyToManyField(User, related_name="answer_vote", blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return (
            f"Answer given by {self.author} to the question {self.question}:{self.text}"
        )

    def get_absolute_url(
        self,
    ):  # Setting the instance of a specific question to the question detail url.
        return reverse("question-detail", kwargs={"pk": self.question_id})

quorabase/templates/quorabase/about.html
{% extends 'quorabase/base.html'%}
{%block content%}
<!-- <h1>What?</h1> -->
{% for question in questions|slice:":1"%}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{question.author.profile.image.url}}" class="img-fluid img-thumbnail" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{question.author.username}}</h5>
        <p class="card-text">{{question.author.profile.about}}</p>
        <p class="card-text"><small class="text-muted">{{question.author.profile.email}}</small></p>
      </div>
    </div>
  </div>
  <div class="card-body">
    <a href="{%url 'user-questions' question.author.username%}" class="card-link ">Questions</a>
    <a href="{%url 'user-answers' question.author.username %}" class="card-link">Answers</a>
  </div>
</div>
{%endfor%}
{%endblock content%}

quorabase/templates/quorabase/answer_confirm_delete.html
{% extends 'quorabase/base.html'%} {%block content%}
<div class="content-section">
  <form action="" method="post">
    {%csrf_token%}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Answer</legend>
      <h3>Are you sure?</h3>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a class="btn btn-outline-secondary" href="{%url 'question-detail' object.id%}">Cancel</a>
    </div>
  </form>
</div>

{%endblock content%}

quorabase/templates/quorabase/answer_form.html
{% extends 'quorabase/base.html'%}
{%load crispy_forms_tags%} {%block content%}
<div class="content-section">
  <form action="" method="post">
    {%csrf_token%}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Quora</legend>
      {{form|crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
  </form>
</div>

{%endblock content%}

quorabase/templates/quorabase/answers.html
{% extends 'quorabase/base.html'%}
{%block content%}
{%if answers%}
{%for answer in answers%}
<article class="media content-section">
  <!-- <img class= "rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt=""> -->
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'about-user' answer.author.username%}">{{ answer.author }}</a>
      <small class="text-muted">{{ answer.date_posted|date:"M d Y D g:i:s"}}</small>
    </div>
    <h2>
      <p>Question by:{{answer.question.author}}</p><a class="article-title"
        href="{%url 'question-detail' answer.question.id %}">{{ answer.question.title }}</a>
    </h2>
    <div class="media content-section">

      <h2 class="article-title"> {{ answer.text }}</h2>
    </div>
  </div>
</article>
{% endfor %}
{%else %}
<h3>
  {{view.kwargs.username}} is yet to answer any questions
</h3>
{%endif%}
{%endblock content%}

quorabase/templates/quorabase/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {%if title%}
  <title>Success</title>
  {%else%}
  <title>Quora</title>
  {%endif%}
  <link rel="stylesheet" href="{% static 'quorabase/main.css'%}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="shortcut icon" type="image/png" href="{% static 'quora.jpeg' %}">

</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Quora</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{%url 'quora-home'%}">Home</a>
            <!-- <a class="nav-item nav-link" href="/about">About</a> -->
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated%}
            <!-- <a class="nav-item active nav-link" href="{%url 'ask-question'%}">Ask question</a> -->
            <a class="nav-item nav-link" href="{%url 'profile'%}">Profile</a>
            <a class="nav-item nav-link" href="{%url 'logout'%}">Logout</a>
            {%else%}
            <a class="nav-item nav-link" href="{%url 'login'%}">Login</a>
            <a class="nav-item nav-link" href="{%url 'register'%}">Register</a>
            {%endif%}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container" ,style="margin-top: 70px;">
    <div class="row">
      <div class="col-md-8">
        {%if messages%}
        {%for message in messages%}
        <div class="alert alert-{{message.tags }}">{{message}}</div>
        {%endfor%}
        {%endif%}
        {% block content %}
        {% endblock content %}
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

quorabase/templates/quorabase/home.html
{%extends "quorabase/base.html"%} {%block content%}
<a class="link-opacity-75-hover" href="{% url 'ask-question' %}">
  <div class="card mb-2 mt-2">
    <div class="card-body">
      <h3 class="fw-bold ">
        What is your question?
      </h3>
    </div>
  </div>
</a>
{%for question in questions%}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ question.author.profile.image.url }}" alt="" />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{%url 'about-user' question.author.username %}">{{ question.author }}</a>
      <small class="text-muted">{{ question.created_at }}</small>
    </div>

    <h2>
      <a class="article-title" href="{%url 'question-detail' question.pk%}">{{ question.title }}</a>
    </h2>
    <!--Question Here-->
    <p class="article-content">{{ question.description }}</p>
    <small class="text-muted"> Likes:{{question.vote.count}} </small>
    <br />
    {% if request.user in question.vote.all%}
    <a href="{%url 'upvote-question' question.id%}" class="btn btn-danger mt-2">Down Vote</a>
    {%else%}
    <a href="{%url 'upvote-question' question.id%}" class="btn btn-success mt-2">Up Vote</a>
    {%endif%}

  </div>
</article>
{%endfor%}
{%endblock content%}

quorabase/templates/quorabase/question_confirm_delete.html
{% extends 'quorabase/base.html'%} {%block content%}
<div class="content-section">
  <form action="" method="post">
    {%csrf_token%}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Post</legend>
      <h3>Are you sure? "{{object.title}}"</h3>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a class="btn btn-outline-secondary" href="{%url 'question-detail' object.id%}">Cancel</a>
    </div>
  </form>
</div>

{%endblock content%}

quorabase/templates/quorabase/question_detail.html
{%extends "quorabase/base.html"%} {%block content%}

<article class="media content-section">
  <img class="rounded-circle article-img" src="{{object.author.profile.image.url}}" alt="" />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{%url 'about-user' question.author.username %}">{{ object.author }}</a>
      <small class="text-muted">{{ object.created_at }}</small>
      {%if object.author == user%}
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{%url 'question-update' object.id%}">Update Question</a>
      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{%url 'question-delete' object.id%}">Delete Question</a>
      {%endif%}
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    <p class="article-content">{{ object.description }}</p>
    <small class="text-muted"> Likes:{{question.vote.count}} </small>
    {% if object.author != user%}
    <a class="btn btn-primary btn-sm mt-1 mb-1" href="{%url 'question-answer' object.id%}">Answer This Question</a>
    {%endif%}
    {% if request.user in question.vote.all%}
    <a href="{%url 'upvote-question' question.id%}" class="btn btn-danger mt-2">Down Vote</a>
    {%else%}
    <a href="{%url 'upvote-question' question.id%}" class="btn btn-success mt-2">Up Vote</a>
    {%endif%}
  </div>
</article>

{%if object.answer_set.count > 0 %} {% for answer in answers%}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{%url 'about-user' answer.author.username %}">{{ answer.author }}</a>
      <small class="text-muted">{{ answer.created_at }}</small>
      {%if answer.author == user%}
      <a class="btn btn-secondary btn-sm mt-1 mb-1"
        href="{%url 'answer-update' object.id answer.id answer.author%}">Update Answer</a>
      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{%url 'answer-delete' object.id answer.id%}">Delete Answer</a>
      {%endif%}
    </div>
    <h2 class="article-title">{{ answer.text }}</h2>
    <small class="text-muted"> Likes:{{answer.vote.count}} </small>
    <br>
    {% if request.user in answer.vote.all%}
    <a href="{%url 'upvote-answer'  answer_id=answer.id%}" class="btn btn-danger mt-2">Down Vote</a>
    {%else%}
    <a href="{%url 'upvote-answer' answer_id=answer.id%}" class="btn btn-success mt-2">Up Vote</a>
    {%endif%}
    <!-- Question Here -->
  </div>
</article>
{%endfor%} {%else%}
<h2>Oops!! No answers yet</h2>
{%endif%} {%endblock content%}

quorabase/templates/quorabase/question_form.html
{% extends 'quorabase/base.html'%} {%load crispy_forms_tags%} {%block content%}
<div class="content-section">
  <form action="" method="post">
    {%csrf_token%}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Quora</legend>
      {{form|crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
  </form>
</div>

{%endblock content%}

quorabase/templates/quorabase/questions.html
{% extends 'quorabase/base.html'%}
{%block content%}
{%if questions%}
{%for question in questions%}
<article class="media content-section">
  <!-- <img class= "rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt=""> -->
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'about-user' question.author.username%}">{{ question.author }}</a>
      <small class="text-muted">{{ question.date_posted|date:"M d Y D g:i:s"}}</small>
    </div>
    <small class="text-muted"> Likes:{{question.vote.count}} </small>
    <h2><a class="article-title" href="{%url 'question-detail' question.id %}">{{ question.title }}</a></h2>
    <p class="article-content">{{ question.description }}</p>
  </div>
</article>
{% endfor %}
{%else %}
<h3>
  {{view.kwargs.username}} is yet to ask any questions
</h3>
{%endif%}
{%endblock content%}